# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/opstuff/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/opstuff/common

PRODUCT_COPY_FILES += \
    vendor/opstuff/common/proprietary/product/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml \
    vendor/opstuff/common/proprietary/system_ext/etc/permissions/privapp-permissions-op-launcher.xml:$(TARGET_COPY_OUT_SYSTEM_SYSTEM)/etc/permissions/privapp-permissions-op-launcher.xml

PRODUCT_COPY_FILES += \
    vendor/opstuff/common/proprietary/product/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/op-launcher-hiddenapi-package-whitelist.xml \
    vendor/opstuff/common/proprietary/system_ext/etc/permissions/privapp-permissions-op-launcher.xml:$(TARGET_COPY_OUT_SYSTEM_PRODUCT)/etc/permissions/privapp-permissions-op-launcher.xml

PRODUCT_PACKAGES += \
    OPGallery \
    OPIconpackOxygen \
    OPIconpackRound \
    OPWeather \
    OPWidget \
    OPLauncher
