LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := OPGallery
LOCAL_MODULE_STEM := OPGallery.apk
LOCAL_SRC_FILES := OPGallery.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/app/OPGallery

include $(BUILD_PREBUILT)
